### ISSUE TITLE
value set by `Cookies.set` with option `path` cannot be read on IE

### ISSUE THREAD

**Issue by PikachuEXE** [ScottHamper/Cookies#32]
Example coffeescript:
```
Cookies.set("key", value, {
        # page specific
        path: window.location.pathname,
        # expire in 1 day
        expires: 24 * 60 * 60,
      })
```
Chrome seems ok with about script, not sure about Firefox/Safari/other browsers.

**Comment by ScottHamper** [comment]
Hey Pikachu,

I'm unable to reproduce this issue. One thing to keep in mind is that using `window.location.pathname` for the `path` option could fail if the pathname includes an extension, e.g., `"/directory/file.html"`.

If you can provide more information for a reliable reproduction case, then I can investigate further. For example, what is the value of `window.location.pathname`? Which exact version of IE are you using?

**Comment by PikachuEXE** [comment]
Sorry, I don't have time until mid-March, will try to reproduce and provide more detail then.
I currently workaround this with some page specific key on cookie name which still works for me.
