### ISSUE TITLE
Support for sub-cookies

### ISSUE THREAD

**Issue by fadetogrey** [ScottHamper/Cookies#39]
Hello Scott,
Would you consider supporting sub-cookies like the following?
Cookies.set('key', 'subkey', 'value');

**Comment by ScottHamper** [comment]
Hey fadetogrey,

No, this is out of the scope of the library. If you'd like to somehow encode extra information into a single cookie value, I'd recommend using JSON.

```javascript
Cookies.set('key', JSON.stringify({ subkey: 'value' }));
JSON.parse(Cookies.get('key')).subkey; // "value"
```
