### ISSUE TITLE
http://rawgit.com/ScottHamper/Cookies/master/dist/cookies.min.js  NOT FOUND

### ISSUE THREAD

**Issue by mateuszjarzewski** [ScottHamper/Cookies#53]
Thank you for changing project path....
Is it make you any good other than breaking people stuff?

Once again, thank you very, very much.

**Comment by ScottHamper** [comment]
Hey @mateuszjarzewski ,

Sorry your page broke! However, the README file clearly describes three different ways to use/install the library, none of which involve directly referencing a file from the master branch. The master branch is the main development branch where all changes/updates take place - including ones that may break backwards compatibility with previous versions. Next time, consider referencing a specific release/tag branch, which will never change.

If you want to continue using rawgit.com, the latest Cookies.js release can be retrieved from:
https://rawgit.com/ScottHamper/Cookies/1.2.2/dist/cookies.min.js
