### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by geniusXboxer** [ScottHamper/Cookies#55]
Hi,

The library ignores the values like $ : while encodingUriComponent for the VALUE to set the cookie.
This breaks certain scenarios. 

encodeUriComponent takes care of all these things and we should simply call it without the regex.
Please fix this or I can PR it.

**Comment by ScottHamper** [comment]
Hey @geniusXboxer,

The `$` character is a valid character for cookie values as specified in [RFC6265](https://www.rfc-editor.org/rfc/rfc6265.txt). As a result, it is not encoded.

Can you describe a reproducible scenario in which having an un-encoded `$` causes a problem?

**Comment by ScottHamper** [comment]
Closing due to months of inactivity.
