### ISSUE TITLE
Comparing to `js-cookie`

### ISSUE THREAD

**Issue by tompazourek** [ScottHamper/Cookies#60]
Hi Scott, awesome work here, thank you.

I was wondering about how the library compares to [`js-cookie`](https://github.com/js-cookie/js-cookie), which seems like a very similar project.

I'd be happy to have some insights as to why use one over another or what makes this library better.

Thanks for any information on this :+1: 

Tom

**Comment by ScottHamper** [comment]
Hey Tomáš,

I briefly discuss some differences in [Issue #54](https://github.com/ScottHamper/Cookies/issues/54). Either library will likely serve your use cases satisfactorily.

When I originally created Cookies.js, js-cookie didn't exist yet - it was still [jquery.cookie](https://github.com/carhartl/jquery-cookie). Back then, not having a dependency on jQuery was a huge plus. These days, js-cookies is a great, mature alternative.

**Comment by tompazourek** [comment]
Thanks for clearing that out. Just what I was looking for.
