### ISSUE TITLE
better way to set Cookies.default 

### ISSUE THREAD

**Issue by AnthonyACE** [ScottHamper/Cookies#61]
I meet the Cookies.expire doesn't work problem, cause by wrong way to set Cookies.default.
My stupid way is that, `Cookies.default = { expires: 3600 }`. 
That stupid mistake will make the Cookies.default.path change to `undefined`, which will cause `Cookies.set('key')` set the cookie at `current path`. 
Then when you use `Cookies.expire('key')` will not expire the Cookie `key` in the `current path`. You can still get the cookie by `Cookie.get('key')`.

**If someone meet the problem that Cookies.expire doesn't work as you wish. Maybe you set the Cookies.default with the stupid way , just like me**

So, which way is the better way to set Cookies.default. 
1. do the assign outside. Cookies.default = assign({}, Cookies.default, { expires: 3600 }).
2. do the assign inside cookie-js. Maybe will need a func `setDefault`, Cookies.setDefault({ expires: 3600 }).just like some other Project . eg: [i18next](https://github.com/i18next/i18next), i18next.init({yourSetting}).

**Comment by ScottHamper** [comment]
Hey @AnthonyACE ,

You can do the following to set the `expires` parameter without overriding other settings:

`Cookies.defaults.expires = 3600;`

**Comment by AnthonyACE** [comment]
Thx a lot
