### ISSUE TITLE
if my cookie value is '👽👽👽👽'  will cause URIError: URI malformed

### ISSUE THREAD

**Issue by linjieAda** [ScottHamper/Cookies#76]

**Comment by ScottHamper** [comment]
Hey @linjieAda ,

Cookie values must be URI encoded in order to comply with RFC6265. See [the relevant section in the README](https://github.com/ScottHamper/Cookies#a-note-about-encoding):

> Cookies.js also expects cookie keys and values to already be URI encoded in a UTF-8 representation when it accesses cookies. Keep this in mind when working with cookies on the server side.
