### ISSUE TITLE
Strange regexp replace

### ISSUE THREAD

**Issue by LastRide** [ScottHamper/Cookies#80]
Hi.

Could you explain please next string of code?

```
value = (value + '').replace(/[^!#$&-+\--:<-\[\]-~]/g, encodeURIComponent);
```

If value would be json - `'[{"name":"test"}]'` would be => `'[{%22name%22:%22test%22}]'`

**Comment by ScottHamper** [comment]
Hey @LastRide ,

The regex is used to replace all characters in the cookie value that are illegal, according to [RFC6265](http://www.rfc-editor.org/rfc/rfc6265.txt), by replacing them with a URI encoded representation (percent encoding).

See the ["A Note About Encoding" section of the README](https://github.com/ScottHamper/Cookies#a-note-about-encoding) for more info.
